variables:
    SOLUTION_DIRECTORY: '${CI_PROJECT_DIR}/HelloEnterprise'

    TAG_VERSION: '${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}'
    
    DOCKER_REPO: registry.gitlab.com/mickvdv/hello-microservice
    KANIKO_IMAGE: gcr.io/kaniko-project/executor:v1.9.1-debug
    BUILD_IMAGE: '${DOCKER_REPO}/build-image:${TAG_VERSION}'


stages:
- build

build:dotnet:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  variables:
    DOCKER_FILE: "${SOLUTION_DIRECTORY}/Dockerfile"
  script:
    - /kaniko/executor 
      --context ${SOLUTION_DIRECTORY}
      --dockerfile ${DOCKER_FILE}
      --destination ${BUILD_IMAGE}

publish:WebAPI:
  needs: ["build:dotnet"]
  variables:
    DOCKER_FILE: "${SOLUTION_DIRECTORY}/HelloEnterprise.WebApi/Dockerfile"
    DOCKER_IMAGE: "${DOCKER_REPO}/web-api"
  stage: build
  image: ${KANIKO_IMAGE}
  script:
  - /kaniko/executor 
    --context ${SOLUTION_DIRECTORY}
    --dockerfile ${DOCKER_FILE}
    --destination ${DOCKER_IMAGE}:${TAG_VERSION}
    --build-arg BASE_IMAGE=${BUILD_BASEIMAGE}
