variables:
    SOLUTION_DIRECTORY: '${CI_PROJECT_DIR}/HelloEnterprise'
    TAG_VERSION: '${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}'
    DOCKER_REPO: registry.gitlab.com/mickvdv/hello-enterprise
    BUILD_IMAGE: '${DOCKER_REPO}/build-image:${TAG_VERSION}'

image:
  name: gcr.io/kaniko-project/executor:v1.9.1-debug
  entrypoint: [""]

before_script:
- echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$CI_DEPENDENCY_PROXY_SERVER\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

build:dotnet:
  script:
    - /kaniko/executor 
      --context ${SOLUTION_DIRECTORY}
      --dockerfile ${SOLUTION_DIRECTORY}/Dockerfile
      --destination ${BUILD_IMAGE}

publish:WebAPI:
  needs: ["build:dotnet"]
  script:
  - /kaniko/executor 
    --context ${SOLUTION_DIRECTORY}
    --dockerfile ${SOLUTION_DIRECTORY}/HelloEnterprise.WebAPI/Dockerfile
    --destination ${DOCKER_REPO}/web-api:${TAG_VERSION}
    --build-arg BUILD_IMAGE=${BUILD_IMAGE}

publish:BackgroundJob:
  needs: ["build:dotnet"]
  script:
  - /kaniko/executor 
    --context ${SOLUTION_DIRECTORY}
    --dockerfile ${SOLUTION_DIRECTORY}/HelloEnterprise.BackgroundJob/Dockerfile
    --destination ${DOCKER_REPO}/background-job:${TAG_VERSION}
    --build-arg BUILD_IMAGE=${BUILD_IMAGE}

publish:Frontend:
  needs: ["build:dotnet"]
  script:
  - /kaniko/executor 
    --context ${SOLUTION_DIRECTORY}
    --dockerfile ${SOLUTION_DIRECTORY}/HelloEnterprise.Frontend/Server/Dockerfile
    --destination ${DOCKER_REPO}/frontend:${TAG_VERSION}
    --build-arg BUILD_IMAGE=${BUILD_IMAGE}
