variables:
    SOLUTION_DIRECTORY: '${CI_PROJECT_DIR}/HelloEnterprise'

    TAG_VERSION: '${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}'
    
    DOCKER_REPO: registry.gitlab.com/mickvdv/hello-microservice
    BUILDER_IMAGE: docker
    BUILD_IMAGE: '${DOCKER_REPO}/build-image:${TAG_VERSION}'


stages:
- build

build:dotnet:
  stage: build
  image: ${BUILDER_IMAGE}
  variables:
    DOCKER_FILE: "${SOLUTION_DIRECTORY}/Dockerfile"
  script:
    - docker build --file ${DOCKER_FILE} -t ${BUILD_IMAGE} ${SOLUTION_DIRECTORY} 
    - docker push ${BUILD_IMAGE}

publish:WebAPI:
  needs: ["build:dotnet"]
  variables:
    DOCKER_FILE: "${SOLUTION_DIRECTORY}/HelloEnterprise.WebApi/Dockerfile"
    DOCKER_IMAGE: "${DOCKER_REPO}/web-api"
  stage: build
  image: ${BUILDER_IMAGE}
  script:
  - docker build --file ${DOCKER_FILE} -t ${DOCKER_IMAGE} ${SOLUTION_DIRECTORY}
  - docker push ${DOCKER_IMAGE}
