variables:
    SOLUTION_DIRECTORY: '${CI_PROJECT_DIR}/HelloEnterprise'

    TAG_VERSION: '${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}'
    
    DOCKER_REPO: registry.gitlab.com/mickvdv/hello-microservice
    KANIKO_IMAGE: gcr.io/kaniko-project/executor:v1.9.1-debug
    BUILD_IMAGE: '${DOCKER_REPO}/build-image:${TAG_VERSION}'


stages:
- build

before_script:
- echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$CI_DEPENDENCY_PROXY_SERVER\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json



build:dotnet:
  stage: build
  image:
    name: ${KANIKO_IMAGE}
    entrypoint: [""]
  variables:
    DOCKER_FILE: "${SOLUTION_DIRECTORY}/Dockerfile"
  script:
    - /kaniko/executor 
      --context ${SOLUTION_DIRECTORY}
      --dockerfile ${DOCKER_FILE}
      --destination ${BUILD_IMAGE}

publish:WebAPI:
  needs: ["build:dotnet"]
  variables:
    DOCKER_FILE: "${SOLUTION_DIRECTORY}/HelloEnterprise.WebApi/Dockerfile"
    DOCKER_IMAGE: "${DOCKER_REPO}/web-api"
  stage: build
  image:
    name: ${KANIKO_IMAGE} 
    entrypoint: [""]
  script:
  - /kaniko/executor 
    --context ${SOLUTION_DIRECTORY}
    --dockerfile ${DOCKER_FILE}
    --destination ${DOCKER_IMAGE}:${TAG_VERSION}
    --build-arg BASE_IMAGE=${BUILD_BASEIMAGE}
